pub const EfusError = error{
    EndOfLine,
    EndOfFile,
    ExtraTokensAfterArguments,
    ExpectedEqualToAfterParamName,
    ExpectedValueAfterEqualTo,
    ExpectedKeyValue,
    UnterminatedString,
    UnexpectedToken,
    InvalidCompcall,
    ArgumentTypeError,
    ArgumentTypeMismatch,
    MissingRequiredArgument,
    UnexpectedArgument,
    TemplateNotFound,
};
